using AutoFixture.Kernel;

using Play.Globalization.Country;

namespace Play.Testing.Emv.AutoFixture.Builders.Globalization;

public class Alpha2CountryCodeBuilder : SpecimenBuilder
{
    #region Static Metadata

    private static readonly List<Alpha2CountryCode> _Alpha2CountryCodeCodes;

    public static readonly SpecimenBuilderId Id = new(nameof(Alpha2CountryCode));

    #endregion

    #region Constructors

    static Alpha2CountryCodeBuilder()
    {
        _Alpha2CountryCodeCodes = GetAlpha2CountryCodes();
    }

    #endregion

    public override SpecimenBuilderId GetId() => Id;

    public override object Create(object request, ISpecimenContext context)
    {
        Type? type = request as Type;

        if (type == null)
            return new NoSpecimen();

        if (type != typeof(Alpha2CountryCode))
            return new NoSpecimen();

        return _Alpha2CountryCodeCodes.ElementAt(_Random.Next(0, _Alpha2CountryCodeCodes.Count - 1));
    }

    private static List<Alpha2CountryCode> GetAlpha2CountryCodes() =>
        new List<Alpha2CountryCode>()
        {
            new Alpha2CountryCode("AF"),
            new Alpha2CountryCode("AX"),
            new Alpha2CountryCode("AL"),
            new Alpha2CountryCode("DZ"),
            new Alpha2CountryCode("AS"),
            new Alpha2CountryCode("AD"),
            new Alpha2CountryCode("AO"),
            new Alpha2CountryCode("AI"),
            new Alpha2CountryCode("AQ"),
            new Alpha2CountryCode("AG"),
            new Alpha2CountryCode("AR"),
            new Alpha2CountryCode("AM"),
            new Alpha2CountryCode("AW"),
            new Alpha2CountryCode("AU"),
            new Alpha2CountryCode("AT"),
            new Alpha2CountryCode("AZ"),
            new Alpha2CountryCode("BS"),
            new Alpha2CountryCode("BH"),
            new Alpha2CountryCode("BD"),
            new Alpha2CountryCode("BB"),
            new Alpha2CountryCode("BY"),
            new Alpha2CountryCode("BE"),
            new Alpha2CountryCode("BZ"),
            new Alpha2CountryCode("BJ"),
            new Alpha2CountryCode("BM"),
            new Alpha2CountryCode("BT"),
            new Alpha2CountryCode("BO"),
            new Alpha2CountryCode("BA"),
            new Alpha2CountryCode("BW"),
            new Alpha2CountryCode("BV"),
            new Alpha2CountryCode("BR"),
            new Alpha2CountryCode("VG"),
            new Alpha2CountryCode("IO"),
            new Alpha2CountryCode("BN"),
             new Alpha2CountryCode("BG"),
             new Alpha2CountryCode("BF"),
             new Alpha2CountryCode("BI"),
             new Alpha2CountryCode("KH"),
             new Alpha2CountryCode("CM"),
             new Alpha2CountryCode("CA"),
             new Alpha2CountryCode("CV"),
             new Alpha2CountryCode("KY"),
             new Alpha2CountryCode("CF"),
             new Alpha2CountryCode("TD"),
             new Alpha2CountryCode("CL"),
             new Alpha2CountryCode("CN"),
             new Alpha2CountryCode("HK"),
             new Alpha2CountryCode("MO"),
             new Alpha2CountryCode("CX"),
             new Alpha2CountryCode("CC"),
             new Alpha2CountryCode("CO"),
             new Alpha2CountryCode("KM"),
             new Alpha2CountryCode("CG"),
             new Alpha2CountryCode("CD"),
             new Alpha2CountryCode("CK"),
             new Alpha2CountryCode("CR"),
             new Alpha2CountryCode("CI"),
             new Alpha2CountryCode("HR"),
             new Alpha2CountryCode("CU"),
             new Alpha2CountryCode("CY"),
             new Alpha2CountryCode("CZ"),
             new Alpha2CountryCode("DK"),
             new Alpha2CountryCode("DJ"),
             new Alpha2CountryCode("DM"),
             new Alpha2CountryCode("DO"),
             new Alpha2CountryCode("EC"),
             new Alpha2CountryCode("EG"),
             new Alpha2CountryCode("SV"),
             new Alpha2CountryCode("GQ"),
             new Alpha2CountryCode("ER"),
             new Alpha2CountryCode("EE"),
             new Alpha2CountryCode("ET"),
             new Alpha2CountryCode("FK"),
             new Alpha2CountryCode("FO"),
             new Alpha2CountryCode("FJ"),
             new Alpha2CountryCode("FI"),
             new Alpha2CountryCode("FR"),
             new Alpha2CountryCode("GF"),
             new Alpha2CountryCode("PF"),
             new Alpha2CountryCode("TF"),
             new Alpha2CountryCode("GA"),
             new Alpha2CountryCode("GM"),
             new Alpha2CountryCode("GE"),
             new Alpha2CountryCode("DE"),
             new Alpha2CountryCode("GH"),
             new Alpha2CountryCode("GI"),
             new Alpha2CountryCode("GR"),
             new Alpha2CountryCode("GL"),
             new Alpha2CountryCode("GD"),
             new Alpha2CountryCode("GP"),
             new Alpha2CountryCode("GU"),
             new Alpha2CountryCode("GT"),
             new Alpha2CountryCode("GG"),
             new Alpha2CountryCode("GN"),
             new Alpha2CountryCode("GW"),
             new Alpha2CountryCode("GY"),
             new Alpha2CountryCode("HT"),
             new Alpha2CountryCode("HM"),
             new Alpha2CountryCode("VA"),
             new Alpha2CountryCode("HN"),
             new Alpha2CountryCode("HU"),
             new Alpha2CountryCode("IS"),
             new Alpha2CountryCode("IN"),
             new Alpha2CountryCode("ID"),
             new Alpha2CountryCode("IR"),
             new Alpha2CountryCode("IQ"),
             new Alpha2CountryCode("IE"),
             new Alpha2CountryCode("IM"),
             new Alpha2CountryCode("IL"),
             new Alpha2CountryCode("IT"),
             new Alpha2CountryCode("JM"),
             new Alpha2CountryCode("JP"),
             new Alpha2CountryCode("JE"),
             new Alpha2CountryCode("JO"),
             new Alpha2CountryCode("KZ"),
             new Alpha2CountryCode("KE"),
             new Alpha2CountryCode("KI"),
             new Alpha2CountryCode("KP"),
             new Alpha2CountryCode("KR"),
             new Alpha2CountryCode("KW"),
             new Alpha2CountryCode("KG"),
             new Alpha2CountryCode("LA"),
             new Alpha2CountryCode("LV"),
             new Alpha2CountryCode("LB"),
             new Alpha2CountryCode("LS"),
             new Alpha2CountryCode("LR"),
             new Alpha2CountryCode("LY"),
             new Alpha2CountryCode("LI"),
             new Alpha2CountryCode("LT"),
             new Alpha2CountryCode("LU"),
             new Alpha2CountryCode("MK"),
             new Alpha2CountryCode("MG"),
             new Alpha2CountryCode("MW"),
             new Alpha2CountryCode("MY"),
             new Alpha2CountryCode("MV"),
             new Alpha2CountryCode("ML"),
             new Alpha2CountryCode("MT"),
             new Alpha2CountryCode("MH"),
             new Alpha2CountryCode("MQ"),
             new Alpha2CountryCode("MR"),
             new Alpha2CountryCode("MU"),
             new Alpha2CountryCode("YT"),
             new Alpha2CountryCode("MX"),
             new Alpha2CountryCode("FM"),
             new Alpha2CountryCode("MD"),
             new Alpha2CountryCode("MC"),
             new Alpha2CountryCode("MN"),
             new Alpha2CountryCode("ME"),
             new Alpha2CountryCode("MS"),
             new Alpha2CountryCode("MA"),
             new Alpha2CountryCode("MZ"),
             new Alpha2CountryCode("MM"),
             new Alpha2CountryCode("NA"),
             new Alpha2CountryCode("NR"),
             new Alpha2CountryCode("NP"),
             new Alpha2CountryCode("NL"),
             new Alpha2CountryCode("AN"),
             new Alpha2CountryCode("NC"),
             new Alpha2CountryCode("NZ"),
             new Alpha2CountryCode("NI"),
             new Alpha2CountryCode("NE"),
             new Alpha2CountryCode("NG"),
             new Alpha2CountryCode("NU"),
             new Alpha2CountryCode("NF"),
             new Alpha2CountryCode("MP"),
             new Alpha2CountryCode("NO"),
             new Alpha2CountryCode("OM"),
             new Alpha2CountryCode("PK"),
             new Alpha2CountryCode("PW"),
             new Alpha2CountryCode("PS"),
             new Alpha2CountryCode("PA"),
             new Alpha2CountryCode("PG"),
             new Alpha2CountryCode("PY"),
             new Alpha2CountryCode("PE"),
             new Alpha2CountryCode("PH"),
             new Alpha2CountryCode("PN"),
             new Alpha2CountryCode("PL"),
             new Alpha2CountryCode("PT"),
             new Alpha2CountryCode("PR"),
             new Alpha2CountryCode("QA"),
             new Alpha2CountryCode("RE"),
             new Alpha2CountryCode("RO"),
             new Alpha2CountryCode("RU"),
             new Alpha2CountryCode("RW"),
             new Alpha2CountryCode("BL"),
             new Alpha2CountryCode("SH"),
             new Alpha2CountryCode("KN"),
             new Alpha2CountryCode("LC"),
             new Alpha2CountryCode("MF"),
             new Alpha2CountryCode("PM"),
             new Alpha2CountryCode("VC"),
             new Alpha2CountryCode("WS"),
             new Alpha2CountryCode("SM"),
             new Alpha2CountryCode("ST"),
             new Alpha2CountryCode("SA"),
             new Alpha2CountryCode("SN"),
             new Alpha2CountryCode("RS"),
             new Alpha2CountryCode("SC"),
             new Alpha2CountryCode("SL"),
             new Alpha2CountryCode("SG"),
             new Alpha2CountryCode("SK"),
             new Alpha2CountryCode("SI"),
             new Alpha2CountryCode("SB"),
             new Alpha2CountryCode("SO"),
             new Alpha2CountryCode("ZA"),
             new Alpha2CountryCode("GS"),
             new Alpha2CountryCode("SS"),
             new Alpha2CountryCode("ES"),
             new Alpha2CountryCode("LK"),
             new Alpha2CountryCode("SD"),
             new Alpha2CountryCode("SR"),
             new Alpha2CountryCode("SJ"),
             new Alpha2CountryCode("SZ"),
             new Alpha2CountryCode("SE"),
             new Alpha2CountryCode("CH"),
             new Alpha2CountryCode("SY"),
             new Alpha2CountryCode("TW"),
             new Alpha2CountryCode("TJ"),
             new Alpha2CountryCode("TZ"),
             new Alpha2CountryCode("TH"),
             new Alpha2CountryCode("TL"),
             new Alpha2CountryCode("TG"),
             new Alpha2CountryCode("TK"),
             new Alpha2CountryCode("TO"),
             new Alpha2CountryCode("TT"),
             new Alpha2CountryCode("TN"),
             new Alpha2CountryCode("TR"),
             new Alpha2CountryCode("TM"),
             new Alpha2CountryCode("TC"),
             new Alpha2CountryCode("TV"),
             new Alpha2CountryCode("UG"),
             new Alpha2CountryCode("UA"),
             new Alpha2CountryCode("AE"),
             new Alpha2CountryCode("GB"),
             new Alpha2CountryCode("US"),
             new Alpha2CountryCode("UM"),
             new Alpha2CountryCode("UY"),
             new Alpha2CountryCode("UZ"),
             new Alpha2CountryCode("VU"),
             new Alpha2CountryCode("VE"),
             new Alpha2CountryCode("VN"),
             new Alpha2CountryCode("VI"),
             new Alpha2CountryCode("WF"),
             new Alpha2CountryCode("EH"),
             new Alpha2CountryCode("YE"),
             new Alpha2CountryCode("ZM"),
             new Alpha2CountryCode("ZW")
        };
}
