using AutoFixture.Kernel;

using Play.Globalization.Country;

namespace Play.Testing.Emv.AutoFixture.Builders.Globalization;

public class NumericCountryCodeBuilder : SpecimenBuilder
{
    #region Static Metadata

    private static readonly List<NumericCountryCode> _NumericCountryCodes;

    public static readonly SpecimenBuilderId Id = new(nameof(NumericCountryCode));

    #endregion

    #region Constructors

    static NumericCountryCodeBuilder()
    {
        _NumericCountryCodes = GetCountryCodes();
    }

    #endregion

    public override SpecimenBuilderId GetId() => Id;

    public override object Create(object request, ISpecimenContext context)
    {
        Type? type = request as Type;

        if (type == null)
            return new NoSpecimen();

        if (type != typeof(NumericCountryCode))
            return new NoSpecimen();

        return _NumericCountryCodes.ElementAt(_Random.Next(0, _NumericCountryCodes.Count - 1));
    }

    private static List<NumericCountryCode> GetCountryCodes() =>
        new List<NumericCountryCode>()
        {
            new NumericCountryCode(4),
            new NumericCountryCode(248),
            new NumericCountryCode(8),
            new NumericCountryCode(12),
            new NumericCountryCode(16),
            new NumericCountryCode(20),
            new NumericCountryCode(24),
            new NumericCountryCode(660),
            new NumericCountryCode(10),
            new NumericCountryCode(28),
            new NumericCountryCode(32),
            new NumericCountryCode(51),
            new NumericCountryCode(533),
            new NumericCountryCode(36),
            new NumericCountryCode(40),
            new NumericCountryCode(31),
            new NumericCountryCode(44),
            new NumericCountryCode(48),
            new NumericCountryCode(50),
            new NumericCountryCode(52),
            new NumericCountryCode(112),
            new NumericCountryCode(56),
            new NumericCountryCode(84),
            new NumericCountryCode(204),
            new NumericCountryCode(60),
            new NumericCountryCode(64),
            new NumericCountryCode(68),
            new NumericCountryCode(70),
            new NumericCountryCode(72),
            new NumericCountryCode(74),
            new NumericCountryCode(76),
            new NumericCountryCode(92),
            new NumericCountryCode(86),
            new NumericCountryCode(96),
            new NumericCountryCode(100),
            new NumericCountryCode(854),
            new NumericCountryCode(108),
            new NumericCountryCode(116),
            new NumericCountryCode(120),
            new NumericCountryCode(124),
            new NumericCountryCode(132),
            new NumericCountryCode(136),
            new NumericCountryCode(140),
            new NumericCountryCode(148),
            new NumericCountryCode(152),
            new NumericCountryCode(156),
            new NumericCountryCode(344),
            new NumericCountryCode(446),
            new NumericCountryCode(162),
            new NumericCountryCode(166),
            new NumericCountryCode(170),
            new NumericCountryCode(174),
            new NumericCountryCode(178),
            new NumericCountryCode(180),
            new NumericCountryCode(184),
            new NumericCountryCode(188),
            new NumericCountryCode(384),
            new NumericCountryCode(191),
            new NumericCountryCode(192),
            new NumericCountryCode(196),
            new NumericCountryCode(203),
            new NumericCountryCode(208),
            new NumericCountryCode(262),
            new NumericCountryCode(212),
            new NumericCountryCode(214),
            new NumericCountryCode(218),
            new NumericCountryCode(818),
            new NumericCountryCode(222),
            new NumericCountryCode(226),
            new NumericCountryCode(232),
            new NumericCountryCode(233),
            new NumericCountryCode(231),
            new NumericCountryCode(238),
            new NumericCountryCode(234),
            new NumericCountryCode(242),
            new NumericCountryCode(246),
            new NumericCountryCode(250),
            new NumericCountryCode(254),
            new NumericCountryCode(258),
            new NumericCountryCode(260),
            new NumericCountryCode(266),
            new NumericCountryCode(270),
            new NumericCountryCode(268),
            new NumericCountryCode(276),
            new NumericCountryCode(288),
            new NumericCountryCode(292),
            new NumericCountryCode(300),
            new NumericCountryCode(304),
            new NumericCountryCode(308),
            new NumericCountryCode(312),
            new NumericCountryCode(316),
            new NumericCountryCode(320),
            new NumericCountryCode(831),
            new NumericCountryCode(324),
            new NumericCountryCode(624),
            new NumericCountryCode(328),
            new NumericCountryCode(332),
            new NumericCountryCode(334),
            new NumericCountryCode(336),
            new NumericCountryCode(340),
            new NumericCountryCode(348),
            new NumericCountryCode(352),
            new NumericCountryCode(356),
            new NumericCountryCode(360),
            new NumericCountryCode(364),
            new NumericCountryCode(368),
            new NumericCountryCode(372),
            new NumericCountryCode(833),
            new NumericCountryCode(376),
            new NumericCountryCode(380),
            new NumericCountryCode(388),
            new NumericCountryCode(392),
            new NumericCountryCode(832),
            new NumericCountryCode(400),
            new NumericCountryCode(398),
            new NumericCountryCode(404),
            new NumericCountryCode(296),
            new NumericCountryCode(408),
            new NumericCountryCode(410),
            new NumericCountryCode(414),
            new NumericCountryCode(417),
            new NumericCountryCode(418),
            new NumericCountryCode(428),
            new NumericCountryCode(422),
            new NumericCountryCode(426),
            new NumericCountryCode(430),
            new NumericCountryCode(434),
            new NumericCountryCode(438),
            new NumericCountryCode(440),
            new NumericCountryCode(442),
            new NumericCountryCode(807),
            new NumericCountryCode(450),
            new NumericCountryCode(454),
            new NumericCountryCode(458),
            new NumericCountryCode(462),
            new NumericCountryCode(466),
            new NumericCountryCode(470),
            new NumericCountryCode(584),
            new NumericCountryCode(474),
            new NumericCountryCode(478),
            new NumericCountryCode(480),
            new NumericCountryCode(175),
            new NumericCountryCode(484),
            new NumericCountryCode(583),
            new NumericCountryCode(498),
            new NumericCountryCode(492),
            new NumericCountryCode(496),
            new NumericCountryCode(499),
            new NumericCountryCode(500),
            new NumericCountryCode(504),
            new NumericCountryCode(508),
            new NumericCountryCode(104),
            new NumericCountryCode(516),
            new NumericCountryCode(520),
            new NumericCountryCode(524),
            new NumericCountryCode(528),
            new NumericCountryCode(530),
            new NumericCountryCode(540),
            new NumericCountryCode(554),
            new NumericCountryCode(558),
            new NumericCountryCode(562),
            new NumericCountryCode(566),
            new NumericCountryCode(570),
            new NumericCountryCode(574),
            new NumericCountryCode(580),
            new NumericCountryCode(578),
            new NumericCountryCode(512),
            new NumericCountryCode(586),
            new NumericCountryCode(585),
            new NumericCountryCode(275),
            new NumericCountryCode(591),
            new NumericCountryCode(598),
            new NumericCountryCode(600),
            new NumericCountryCode(604),
            new NumericCountryCode(608),
            new NumericCountryCode(612),
            new NumericCountryCode(616),
            new NumericCountryCode(620),
            new NumericCountryCode(630),
            new NumericCountryCode(634),
            new NumericCountryCode(638),
            new NumericCountryCode(642),
            new NumericCountryCode(643),
            new NumericCountryCode(646),
            new NumericCountryCode(652),
            new NumericCountryCode(654),
            new NumericCountryCode(659),
            new NumericCountryCode(662),
            new NumericCountryCode(663),
            new NumericCountryCode(666),
            new NumericCountryCode(670),
            new NumericCountryCode(882),
            new NumericCountryCode(674),
            new NumericCountryCode(678),
            new NumericCountryCode(682),
            new NumericCountryCode(686),
            new NumericCountryCode(688),
            new NumericCountryCode(690),
            new NumericCountryCode(694),
            new NumericCountryCode(702),
            new NumericCountryCode(703),
            new NumericCountryCode(705),
            new NumericCountryCode(90),
            new NumericCountryCode(706),
            new NumericCountryCode(710),
            new NumericCountryCode(239),
            new NumericCountryCode(728),
            new NumericCountryCode(724),
            new NumericCountryCode(144),
            new NumericCountryCode(736),
            new NumericCountryCode(740),
            new NumericCountryCode(744),
            new NumericCountryCode(748),
            new NumericCountryCode(752),
            new NumericCountryCode(756),
            new NumericCountryCode(760),
            new NumericCountryCode(158),
            new NumericCountryCode(762),
            new NumericCountryCode(834),
            new NumericCountryCode(764),
            new NumericCountryCode(626),
            new NumericCountryCode(768),
            new NumericCountryCode(772),
            new NumericCountryCode(776),
            new NumericCountryCode(780),
            new NumericCountryCode(788),
            new NumericCountryCode(792),
            new NumericCountryCode(795),
            new NumericCountryCode(796),
            new NumericCountryCode(798),
            new NumericCountryCode(800),
            new NumericCountryCode(804),
            new NumericCountryCode(784),
            new NumericCountryCode(826),
            new NumericCountryCode(840),
            new NumericCountryCode(581),
            new NumericCountryCode(858),
            new NumericCountryCode(860),
            new NumericCountryCode(548),
            new NumericCountryCode(862),
            new NumericCountryCode(704),
            new NumericCountryCode(850),
            new NumericCountryCode(876),
            new NumericCountryCode(732),
            new NumericCountryCode(887),
            new NumericCountryCode(894),
            new NumericCountryCode(716)
        };
}
